# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [2]:
a = 2.0 + 3.0/5.0 == 10
a

False

In [3]:
b = (a+10.2) - 5.0 * 2.0 <= 2.9
b 

True

In [4]:
c = 10 <= a / b + 33.8 < 100
c

True

In [6]:
d = 5 != a / (b + c)
d

True

In [7]:
e = 33 == d * 2
e

False

## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [8]:
('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)

False

In [12]:
('a',1,True,'b',0,False) == ('a',True,1,'b',False,0)

True

In [14]:
['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)

True

In [15]:
['a',1,True,'b',0,False] == ('a',True,1,'b',False,0)

False

In [ ]:
['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]

False

In [ ]:
['a',1,True,'b',0,False] == ['a',True,1,'b',False,0]

In [18]:
['a',1,True,'b',0,False] > ['a',True,1]

True

In [19]:
['a',1,True,'b',0,False] < ['a',True,1]

False

In [20]:
['a',1,True,'b',0,False] == 1

False

In [22]:
['a',1,True,'b',0,False] != 1

True

In [23]:
['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

True

In [24]:
['a',True,1] < ['a',True,1] < ['a',1,True,'b',0,False]

False

## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [34]:
#o objeto foi transformado para .csv ao final do exercício anterior
import pandas as pd
df3 = pd.read_csv("comp_1.csv", index_col="Unnamed: 0")
df3 = df3.round(3)
df3

,ultima_linha,ultima_coluna
numero_de_valores,4.000,7.000
media,25.407,34.590
std,10.603,29.495
min,16.224,5.292
25%,16.224,11.828
50%,25.407,34.590
75%,34.590,45.795
max,34.590,87.000


## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [35]:
import numpy as np
array4 = np.ones(df3.shape, dtype=int)
array4

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [36]:
df3.to_numpy() == array4

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [37]:
df3.to_numpy() > array4

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [39]:
df3.to_numpy() <= array4

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [41]:
(0 < df3.to_numpy()) & (df3.to_numpy() < 1)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [ ]:
ex9 = df3.iloc[1,:]
ex9
ex9_1 = ex9 <= 5
#count não funcionou pq count não funciona em pandas?
(ex9_1 == False).sum()

np.int64(2)

## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [51]:
ex9 = df3.iloc[1,:]
ex9
ex9_2 = ex9 >= 5
(ex9_2 == False).sum()

np.int64(0)