# Exercício:

## 01 – Cite três vantagens do uso das funções e duas características que toda função deva ter?

R.: Algumas vantagens de funções que podemos citar são:
 - Uma função pode ser escrita uma única vez e reutilizadas diversas vezes;
 - Uma função é mais organizada e fácil de entender do que um código usando diferentes métodos e características de um objeto;
 - É mais fácil alterar uma coisa quando se está usando uma função, pois pode ser alterado somente na função criada e não todo o código.
 Além disso, uma função deve ser curta, simples, clara e fácil de ser entendida.

## Responda a pergunta do exercício 2 da aula 10, usando funções:<br>
Instancie um objeto da classe NumPy array, contendo 5 valores quantitativos randômicos normalmente distribuídos, com média 10 e desvio padrão 3.<br><br>
Quantos e quais são os valores superiores a 10?

In [ ]:
import numpy as np
def array_5valores():
    array = np.random.normal(loc=10, scale=3, size=5)
    return array
def count_maiores_que_10():
    count = (array > 10).sum()
    return count
import numpy as np

def array_5valores():
    array = np.random.normal(loc=10, scale=3, size=5)
    return array

def count_maiores_que_10(array):
    count = (array > 10).sum()
    return count

valores = array_5valores()
quantidade = count_maiores_que_10(valores)
print(valores)
print(quantidade)

[ 8.39351218  8.44480769 11.25688744 10.94324264  9.67665912]
2
[ 8.39351218  8.44480769 11.25688744 10.94324264  9.67665912]
2


## 02 – Descreva o racional da sua resposta:

R.: Foi utilizada a mesma lógica que no exercício dois da aula dez. Primeiro foi definida uma função criava uma Numpy Array com as especificações desejadas. Depois foi feito uma segunda função que calculava os valores nessa array que eram maiores que 10. 

## 03 – Desenhe o fluxograma da resposta:

## 04 – Escreva o programa em Python:

In [ ]:
import numpy as np
def array_5valores():
    array = np.random.normal(loc=10, scale=3, size=5)
    return array
def count_maiores_que_10():
    count = (array > 10).sum()
    return count
import numpy as np

def array_5valores():
    array = np.random.normal(loc=10, scale=3, size=5)
    return array

def count_maiores_que_10(array):
    count = (array > 10).sum()
    return count

valores = array_5valores()
quantidade = count_maiores_que_10(valores)
print(valores)
print(quantidade)

## 05 – Seria possível, com o racional proposto, saber quantos e quais valores são superiores a 20? Porque?

Sim, seria possível, basta usar a mesma lógica.

In [10]:
import numpy as np
def array_5valores():
    array = np.random.normal(loc=10, scale=3, size=5)
    return array
def count_maiores_que_20():
    count = (array > 20).sum()
    return count
import numpy as np

def array_5valores():
    array = np.random.normal(loc=10, scale=3, size=5)
    return array

def count_maiores_que_10(array):
    count = (array > 10).sum()
    return count

valores = array_5valores()
quantidade = count_maiores_que_10(valores)
print(valores)
print(quantidade)

[ 6.76080174 13.82450618 14.53267524 10.75773359  7.1378973 ]
3


## Desenvolva um programa de computador que retorne a média de um conjunto de valores.

In [16]:
import numpy as np
array = np.random.normal(size=20)
def Encontrar_media(array):
    return np.mean(array)
resposta = Encontrar_media (array)
print(array)
print(resposta)

[ 0.38186287 -1.01718629 -0.79058958  0.6832871   0.84603651 -0.58799562
  2.16423554 -1.27551189 -0.62062038  2.00982264 -1.89837811 -0.13219326
  1.52391485  0.10234371  0.96732895  0.19585796 -0.00790454  0.09294107
  0.03410583 -0.56250388]
0.10544267566349723


## 06 – Descreva o racional da sua resposta:

R.: A função funciona para encontrar a média de qualquer objeto, basca colocar ele entre parênteses.

## 07 – Desenhe o fluxograma da resposta:

## 07 – Escreva o programa em Python:

In [ ]:
import numpy as np
array = np.random.normal(size=20)
def Encontrar_media(array):
    return np.mean(array)
resposta = Encontrar_media (array)
print(array)
print(resposta)

## 09 – Desenvolva um programa de computador que retorne a divisão de dois objetos simples. Seu programa deve ser capaz de reconhecer a classe destes objetos e o valor, antes de retornar ao usuário.

In [31]:
x = 12
y = 6
def dividir_valores(x,y):
    print(y)
    print(x)
    print (type(x))
    print(type(y))
    resultado = x / y
    return resultado
resposta2 = dividir_valores(x,y)
resposta2



6
12
<class 'int'>
<class 'int'>


2.0

## 10 – Desenvolva um programa de computador que retorne a divisão de dois objetos compostos. Seu programa deve ser capaz de reconhecer a classe destes objetos e o valor, antes de retornar ao usuário.

In [34]:
x = np.random.normal(size=3)
y = np.random.normal(size=3)
def dividir_valores(x,y):
    print(y)
    print(x)
    print (type(x))
    print(type(y))
    resultado = x / y
    return resultado
resposta3 = dividir_valores(x,y)
print(resposta3)


[ 0.59692152  1.56410748 -2.08281936]
[ 0.01163688 -0.432407    0.01150976]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 0.01949483 -0.27645607 -0.00552605]
