# Exercício:

## 01 – Dados as operações abaixo, em Python, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Imprima os objetos e o resultado usando uma estrutura condicional.

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [ ]:
p = 2.0 + 3.0 / 5.0 == 10
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
r = 10 <= p / q + 33.8 < 100
s = 5 != p / (q + r)
t = 33 == s * 2
if p == True:
    print("You got it!!")
else:
    print("Try again!")
    print ("Right Answer =")
    print(2.0 + 3.0 / 5.0)

Try again!
Right Answer =
2.6


In [14]:
if q == True:
    print("You got it!!")
else:
    print("Try again!")
    print ("Right Answer =")
    print((p + 10.2) - 5.0 * 2.0)

You got it!!


In [15]:
if r == True:
    print("You got it!!")
else:
    print("Try again!")
    print ("Right Answer =")
    print(10 <= p / q + 33.8)

You got it!!


In [16]:
if s == True:
    print("You got it!!")
else:
    print("Try again!")
    print ("Right Answer =")
    print(p / (q + r))

You got it!!


In [17]:
if t == True:
    print("You got it!!")
else:
    print("Try again!")
    print ("Right Answer =")
    print(s * 2)

Try again!
Right Answer =
2


## Instancie um objeto da classe array numpy, contendo 5 valores quantitativos randômicos normalmente distribuídos, com média 10 e desvio padrão 3. 
Quantos e quais são os valores superiores a 10?

In [ ]:
import numpy as np
array1 = np.random.normal(loc=10, scale=3, size=5)
print(array1)
ex1 = array1[array1 > 10]
print("Quantos valores são maiores que 10:")
print(len(array1))
print("Quais são os valores:")
print(ex1)

[ 8.27850123 13.3632022   7.00885741 12.68631743 15.57421333]
Quantos valores sâo maiores que 10:
5
Quais são os valores:
[13.3632022  12.68631743 15.57421333]


## 02 – Descreva o racional da sua resposta:

R.: Para criar um array com valores qauntitativos rândomicos com distribuição normal usa-se o método np.random.normal(), depois procurei métodos que pudessem definir o valor médio dos valores = loc="x", um que definisse o desvio padrão = scale="y" e um que definisse o tamanho do array = size = "z". Em seguida usei métodos usados anteriormente e operadores relacionais para definir quantos valores eram maiores que 10 e criar um array com esses valores.

## 03 – Desenhe o fluxograma da resposta:

<img src="./img/Diagrama10_3.png" width="400" />

## 04 – Escreva o programa em Python:

In [26]:
import numpy as np
array1 = np.random.normal(loc=10, scale=3, size=5)
array1
ex1 = array1[array1 > 10]
print("Quantos valores sâo maiores que 10:")
print(len(ex1))
print("Quais são os valores:")
print(ex1)

Quantos valores sâo maiores que 10:
3
Quais são os valores:
[10.17277292 15.53024596 12.52245305]


## 05 – Seria possível, com o racional proposto, saber quantos e quais valores são superiores a 20? Porque?

Sim, seria possível, para isso basta modificar o 10 pelo 20 no código anterior

In [29]:
ex5 = array1[array1 > 20]
print("Quantos valores sâo maiores que 20:")
print(len(ex5))
print("Quais são os valores:")
print(ex5)

Quantos valores sâo maiores que 20:
0
Quais são os valores:
[]


## 06 – Instancie um objeto da classe lista com os valores obtidos no exercício 02.

O valor 10.453444246931676 está presente?

In [35]:
ex2 = [8.27850123, 13.3632022, 7.00885741, 12.68631743, 15.57421333]
ex2
print("O valor 10.453444246931676 está presente em ex2?")
10.453444246931676 in ex2

O valor 10.453444246931676 está presente em ex2?


False

## No exercício 7 da aula 6, foi instanciado um objeto da classe DataFrame. Exporte (usando nome_data_frame.to_csv(‘nome_arquivo.csv’)) para .csv estes dados e os importe (com pd.read_csv(‘nome_arquivo.csv’) aqui. Edite o objeto para que os index sejam os nomes dos genes e para que as colunas sejam facilmente identificadas. Usando o número de caracteres do primeiro gene, quero saber a informação gênica. Caso o nome tenha entre 2 e 4 caracteres inclusive, posso saber as informações do gene? Porém, caso tenha menos de 2 caracteres, posso saber todos os valores nas instâncias onde os números de caracteres dos nomes são superiores a 4? Ainda, caso tenha mais de 4 caracteres, apenas me informe quem é superior.


In [1]:
import pandas as pd
import numpy as np
listex6 = pd.read_csv("df.csv", index_col="Unnamed: 0")
listex6
#A lista já havia sido ajustada no exercício da aula 6

primeiro_gene = listex6.index[0]
n = listex6.loc[primeiro_gene, "num_Caracteres"]
if 2 <= n <= 4:
    print("Informações completas:")
    print(listex6)
if n < 2:
    print("Genes com mais de 4 caracteres:")
    print(listex6[listex6["num_Caracteres"] > 4])
else:  # n > 4
    print("Genes superiores a 4 caracteres:")
    print(listex6.index[listex6["num_Caracteres"] > 4])

Genes superiores a 4 caracteres:
Index(['PPARG', 'ADRB2', 'TCF7L2', 'FABP2', 'NOTCH2'], dtype='object')


## 07 – Descreva o racional da sua resposta:

R.: Primeiro selecionei as informações de interesse, selecionando primeiro a linha, tentei selecionar usando iloc mas como não estava conseguindo, nomeei primeiro a linha usando a indexação e selecionei a coluna com o número de caractéres, depois utilizei operações condicionais para aplicar a lógica pedida, imprimindo ou a DataFrame completaa ou a DataFrame filtrada.


## 08 – Desenhe o fluxograma da resposta:

<img src="./img/Diagrama10_8.png" width="400" />

## 09 – Escreva o programa em Python:

In [2]:
listex6 = pd.read_csv("df.csv", index_col="Unnamed: 0")
listex6
#A lista já havia sido ajustada no exercício da aula 6
primeiro_gene = listex6.index[0]
n = listex6.loc[primeiro_gene, "num_Caracteres"]
if 2 <= n <= 4:
    print("Informações completas:")
    print(listex6)
if n < 2:
    print("Genes com mais de 4 caracteres:")
    print(listex6[listex6["num_Caracteres"] > 4])
else:  # n > 4
    print("Genes superiores a 4 caracteres:")
    print(listex6[listex6["num_Caracteres"] > 4])

Genes superiores a 4 caracteres:
        num_Caracteres    Iniciais  Count_A  tem_hu
PPARG                5  ['P', 'P']        1   False
ADRB2                5  ['A', 'D']        1   False
TCF7L2               6  ['T', 'C']        0   False
FABP2                5  ['F', 'A']        1   False
NOTCH2               6  ['N', 'O']        0   False


## 10 – Caso a DataFrame contenha 10 milhões de entradas, este racional utilizado poderia responder as mesmas perguntas? Porque?

R.:  Teoricamente seria possível utilizar o mesmo racional para um DataFrame de qualquer tamanho, no entanto iria consumir muita memória da máquina e poderia travar dependendo da máquina utilizada. 